on:
  workflow_run:
    workflows: ["Generate README.md"]
      types:
        - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
      with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.USER_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"
