on:
  workflow_run:
    workflows: ["Update README.md"]
    types:
        - completed
jobs:
  add_stats:
    runs-on: ubuntu-latest
    steps:
    - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
      with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.WAKA_GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "True"
          LOCALE: "en"
          SHOW_UPDATED_DATE: "True"
          DEBUG_LOGGING: "True"
