name: "Update README.md"
on:
  schedule:
    - cron: '0 2 * * *' # at 2:00
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: yoshi389111/github-profile-3d-contrib@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ github.repository_owner }}
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v3
      with:
        token: ${{ secrets.USER_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name "Seba Cornejo"
        git config user.email scornejo[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push
        fi
